-- DDL (Data Definition Language)

CREATE DATABASE HealthClinicDb;

USE HealthClinicDb;

CREATE TABLE [Address] (
	Id INT PRIMARY KEY IDENTITY,
	CEP CHAR(8) NOT NULL,
	UF CHAR(2) NOT NULL,
	City VARCHAR(50) NOT NULL,
	Neighborhood VARCHAR(50) NOT NULL,
	Number SMALLINT NOT NULL
);

ALTER TABLE [Address]
ADD Street VARCHAR(50) NOT NULL;

ALTER TABLE [Address]
ADD Complement VARCHAR(50);

CREATE TABLE Clinic (
	Id INT PRIMARY KEY IDENTITY,
	AddressId INT FOREIGN KEY REFERENCES [Address](Id) NOT NULL UNIQUE,
	FancyName VARCHAR(50) NOT NULL,
	CompanyName VARCHAR(70) NOT NULL,
	OpeningTime TIME NOT NULL,
	CLosingTime TIME NOT NULL
);

CREATE TABLE UserType (
	Id INT PRIMARY KEY IDENTITY,
	TypeName VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE [User] (
	Id INT PRIMARY KEY IDENTITY,
	AddressId INT FOREIGN KEY REFERENCES [Address](Id) NOT NULL,
	UserTypeId INT FOREIGN KEY REFERENCES UserType(Id) NOT NULL,
	[Name] VARCHAR(60) NOT NULL, 
	Email VARCHAR(100) NOT NULL UNIQUE,
	BirthDate Date NOT NULL,
	PhoneNumber VARCHAR(11),
	SomeonePhoneNumber VARCHAR(11),
	[Password] VARCHAR(128) NOT NULL
);

CREATE TABLE Doctor (
	Id INT PRIMARY KEY IDENTITY,
	UserId INT FOREIGN KEY REFERENCES [User](Id) NOT NULL UNIQUE,
	CRM CHAR(8) NOT NULL UNIQUE
);

CREATE TABLE ClinicDoctor (
	Id INT PRIMARY KEY IDENTITY,
	ClinicId INT FOREIGN KEY REFERENCES Clinic(Id) NOT NULL,
	DoctorId INT FOREIGN KEY REFERENCES Doctor(Id) NOT NULL
);

CREATE TABLE MedicalSpecialty (
	Id INT PRIMARY KEY IDENTITY,
	[Name] VARCHAR(40) NOT NULL UNIQUE
);

CREATE TABLE DoctorMedicalSpecialty (
	Id INT PRIMARY KEY IDENTITY,
	DoctorId INT FOREIGN KEY REFERENCES Doctor(Id) NOT NULL,
	MedicalSpecialtyId INT FOREIGN KEY REFERENCES MedicalSpecialty(Id) NOT NULL,
);

CREATE TABLE Patient (
	Id INT PRIMARY KEY IDENTITY,
	UserId INT FOREIGN KEY REFERENCES [User](Id) NOT NULL UNIQUE
);

CREATE TABLE ClinicPatient (
	Id INT PRIMARY KEY IDENTITY,
	ClinicId INT FOREIGN KEY REFERENCES Clinic(Id) NOT NULL,
	PatientId INT FOREIGN KEY REFERENCES Patient(Id) NOT NULL
);

CREATE TABLE MedicalRecord (
	Id INT PRIMARY KEY IDENTITY,
	[Text] VARCHAR(3000) NOT NULL
);

CREATE TABLE ConsultationStatus (
	Id INT PRIMARY KEY IDENTITY,
	StatusName VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE Consultation (
	Id INT PRIMARY KEY IDENTITY,
	ClinicId INT FOREIGN KEY REFERENCES Clinic(Id) NOT NULL,
	PatientId INT FOREIGN KEY REFERENCES Patient(Id) NOT NULL,
	DoctorMedicalSpecialtyId INT FOREIGN KEY REFERENCES DoctorMedicalSpecialty(Id) NOT NULL,
	MedicalRecordId INT FOREIGN KEY REFERENCES MedicalRecord(Id),
	ConsultationStatusId INT FOREIGN KEY REFERENCES ConsultationStatus(Id) NOT NULL,
	[Date] Date NOT NULL,
	[Time] TIME NOT NULL
);

CREATE TABLE Comment (
	Id INT PRIMARY KEY IDENTITY,
	ConsultationId INT FOREIGN KEY REFERENCES Consultation(Id) NOT NULL,
	[Date] Date NOT NULL,
	[Text] VARCHAR(400) NOT NULL,
	IsValidated BIT NOT NULL DEFAULT 0
);

-- DROP TABLE Consultation;
-- DROP DATABASE HealthClinicDb;